import type { Metadata } from "next";
import "@/styles/globals.css";
import "@/styles/fontawesome-free-6.5.2-web/css/all.min.css";
import { TitleComponentContextProvider } from "@/context/TitleComponentContext";
import { MenuSidebarProvider } from "@/context/MenuSidebarContext";
import Sidebar from "@/components/common/Sidebar";
import PanelContainer from "@/components/common/PanelContainer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
 

import '@/styles/prosemirror.css'
export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <>
      <MenuSidebarProvider>
      <ToastContainer theme="dark" />
        <Sidebar />
        <TitleComponentContextProvider>
          <PanelContainer>
            {children}
          </PanelContainer>

        </TitleComponentContextProvider>
      </MenuSidebarProvider>


    </>
  );
}
